### ISSUE TITLE
server folder is not available anymore in master branch

### ISSUE THREAD

**Issue by harimayco** [Hash-Studios/eco_commerce_app#21]
Hello,

First I want to Thank you for your hardwork making this nice and clean app, I hope I can contribute to this awesome project!
but I read from readme 
`master branch has backend enabled`

but the server folder has been removed from the master branch.
how can I duplicate the backend in order to run the app with api for my local environment?

Thanks! 👍

**Comment by LiquidatorCoder** [comment]
Actually, we hadn't included the server in this repo. `master branch has backend enabled` meant that anyone can add their server/API to the master branch for full functionality.

We had used Strapi CMS for the backend. Here are some docs for [getting started](https://strapi.io/documentation/v3.x/getting-started/quick-start.html#_4-create-a-category-content-type) with Strapi.

I will be closing this issue.
If you have any other problem feel free to open a new issue.
